name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Run Tests
        run: go test -json ./... > test_results.json

      - name: Annotate Tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.6.0
        with:
          test-results: test_results.json
